//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFatoorah.Test
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MerchantDC", Namespace="http://tempuri.org/")]
    public partial class MerchantDC : object
    {
        
        private string merchant_codeField;
        
        private string merchant_usernameField;
        
        private string merchant_passwordField;
        
        private string merchant_ReferenceIDField;
        
        private string ReturnURLField;
        
        private string merchant_error_urlField;
        
        private string udf1Field;
        
        private string udf2Field;
        
        private string udf3Field;
        
        private string udf4Field;
        
        private string udf5Field;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string merchant_code
        {
            get
            {
                return this.merchant_codeField;
            }
            set
            {
                this.merchant_codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string merchant_username
        {
            get
            {
                return this.merchant_usernameField;
            }
            set
            {
                this.merchant_usernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string merchant_password
        {
            get
            {
                return this.merchant_passwordField;
            }
            set
            {
                this.merchant_passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string merchant_ReferenceID
        {
            get
            {
                return this.merchant_ReferenceIDField;
            }
            set
            {
                this.merchant_ReferenceIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ReturnURL
        {
            get
            {
                return this.ReturnURLField;
            }
            set
            {
                this.ReturnURLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string merchant_error_url
        {
            get
            {
                return this.merchant_error_urlField;
            }
            set
            {
                this.merchant_error_urlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string udf1
        {
            get
            {
                return this.udf1Field;
            }
            set
            {
                this.udf1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string udf2
        {
            get
            {
                return this.udf2Field;
            }
            set
            {
                this.udf2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string udf3
        {
            get
            {
                return this.udf3Field;
            }
            set
            {
                this.udf3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string udf4
        {
            get
            {
                return this.udf4Field;
            }
            set
            {
                this.udf4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string udf5
        {
            get
            {
                return this.udf5Field;
            }
            set
            {
                this.udf5Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PayRequestDCV1", Namespace="http://tempuri.org/")]
    public partial class PayRequestDCV1 : object
    {
        
        private MyFatoorah.Test.CustomerDC CustomerDCField;
        
        private MyFatoorah.Test.MerchantDC MerchantDCField;
        
        private MyFatoorah.Test.ProductDC[] lstProductDCField;
        
        private MyFatoorah.Test.TotalDC totalDCField;
        
        private MyFatoorah.Test.PaymentModeDC paymentModeDCField;
        
        private MyFatoorah.Test.PaymentCurrencyDC paymentCurrencyDCField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MyFatoorah.Test.CustomerDC CustomerDC
        {
            get
            {
                return this.CustomerDCField;
            }
            set
            {
                this.CustomerDCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MyFatoorah.Test.MerchantDC MerchantDC
        {
            get
            {
                return this.MerchantDCField;
            }
            set
            {
                this.MerchantDCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MyFatoorah.Test.ProductDC[] lstProductDC
        {
            get
            {
                return this.lstProductDCField;
            }
            set
            {
                this.lstProductDCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MyFatoorah.Test.TotalDC totalDC
        {
            get
            {
                return this.totalDCField;
            }
            set
            {
                this.totalDCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public MyFatoorah.Test.PaymentModeDC paymentModeDC
        {
            get
            {
                return this.paymentModeDCField;
            }
            set
            {
                this.paymentModeDCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public MyFatoorah.Test.PaymentCurrencyDC paymentCurrencyDC
        {
            get
            {
                return this.paymentCurrencyDCField;
            }
            set
            {
                this.paymentCurrencyDCField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerDC", Namespace="http://tempuri.org/")]
    public partial class CustomerDC : object
    {
        
        private string NameField;
        
        private string EmailField;
        
        private string MobileField;
        
        private string GenderField;
        
        private string DOBField;
        
        private string CountryCodeField;
        
        private string civil_idField;
        
        private string AreaField;
        
        private string BlockField;
        
        private string StreetField;
        
        private string AvenueField;
        
        private string BuildingField;
        
        private string FloorField;
        
        private string ApartmentField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Mobile
        {
            get
            {
                return this.MobileField;
            }
            set
            {
                this.MobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DOB
        {
            get
            {
                return this.DOBField;
            }
            set
            {
                this.DOBField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CountryCode
        {
            get
            {
                return this.CountryCodeField;
            }
            set
            {
                this.CountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string civil_id
        {
            get
            {
                return this.civil_idField;
            }
            set
            {
                this.civil_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Area
        {
            get
            {
                return this.AreaField;
            }
            set
            {
                this.AreaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Block
        {
            get
            {
                return this.BlockField;
            }
            set
            {
                this.BlockField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Street
        {
            get
            {
                return this.StreetField;
            }
            set
            {
                this.StreetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Avenue
        {
            get
            {
                return this.AvenueField;
            }
            set
            {
                this.AvenueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Building
        {
            get
            {
                return this.BuildingField;
            }
            set
            {
                this.BuildingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Floor
        {
            get
            {
                return this.FloorField;
            }
            set
            {
                this.FloorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Apartment
        {
            get
            {
                return this.ApartmentField;
            }
            set
            {
                this.ApartmentField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TotalDC", Namespace="http://tempuri.org/")]
    public partial class TotalDC : object
    {
        
        private double subtotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double subtotal
        {
            get
            {
                return this.subtotalField;
            }
            set
            {
                this.subtotalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentModeDC", Namespace="http://tempuri.org/")]
    public partial class PaymentModeDC : object
    {
        
        private string paymentModeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string paymentMode
        {
            get
            {
                return this.paymentModeField;
            }
            set
            {
                this.paymentModeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentCurrencyDC", Namespace="http://tempuri.org/")]
    public partial class PaymentCurrencyDC : object
    {
        
        private string paymentCurrrencyField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string paymentCurrrency
        {
            get
            {
                return this.paymentCurrrencyField;
            }
            set
            {
                this.paymentCurrrencyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDC", Namespace="http://tempuri.org/")]
    public partial class ProductDC : object
    {
        
        private string product_nameField;
        
        private double unitPriceField;
        
        private int qtyField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string product_name
        {
            get
            {
                return this.product_nameField;
            }
            set
            {
                this.product_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double unitPrice
        {
            get
            {
                return this.unitPriceField;
            }
            set
            {
                this.unitPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int qty
        {
            get
            {
                return this.qtyField;
            }
            set
            {
                this.qtyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PayResponseDC", Namespace="http://tempuri.org/")]
    public partial class PayResponseDC : object
    {
        
        private string ResponseCodeField;
        
        private string referenceIDField;
        
        private string ResponseMessageField;
        
        private string paymentURLField;
        
        private double net_amountField;
        
        private int invoiceNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                this.ResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string referenceID
        {
            get
            {
                return this.referenceIDField;
            }
            set
            {
                this.referenceIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ResponseMessage
        {
            get
            {
                return this.ResponseMessageField;
            }
            set
            {
                this.ResponseMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string paymentURL
        {
            get
            {
                return this.paymentURLField;
            }
            set
            {
                this.paymentURLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double net_amount
        {
            get
            {
                return this.net_amountField;
            }
            set
            {
                this.net_amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int invoiceNumber
        {
            get
            {
                return this.invoiceNumberField;
            }
            set
            {
                this.invoiceNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOrderStatusRequestDC", Namespace="http://tempuri.org/")]
    public partial class GetOrderStatusRequestDC : object
    {
        
        private string merchant_codeField;
        
        private string merchant_usernameField;
        
        private string merchant_passwordField;
        
        private string referenceIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string merchant_code
        {
            get
            {
                return this.merchant_codeField;
            }
            set
            {
                this.merchant_codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string merchant_username
        {
            get
            {
                return this.merchant_usernameField;
            }
            set
            {
                this.merchant_usernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string merchant_password
        {
            get
            {
                return this.merchant_passwordField;
            }
            set
            {
                this.merchant_passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string referenceID
        {
            get
            {
                return this.referenceIDField;
            }
            set
            {
                this.referenceIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderStatusResponseDC", Namespace="http://tempuri.org/")]
    public partial class OrderStatusResponseDC : object
    {
        
        private string ResponseCodeField;
        
        private string PayTxnIDField;
        
        private string ResponseMessageField;
        
        private string PaymodeField;
        
        private string resultField;
        
        private double gross_amountField;
        
        private double net_amountField;
        
        private string AuthIDField;
        
        private string PostDateField;
        
        private string TransIDField;
        
        private string RefIDField;
        
        private string OrderIDField;
        
        private string udf1Field;
        
        private string udf2Field;
        
        private string udf3Field;
        
        private string udf4Field;
        
        private string udf5Field;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                this.ResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PayTxnID
        {
            get
            {
                return this.PayTxnIDField;
            }
            set
            {
                this.PayTxnIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ResponseMessage
        {
            get
            {
                return this.ResponseMessageField;
            }
            set
            {
                this.ResponseMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Paymode
        {
            get
            {
                return this.PaymodeField;
            }
            set
            {
                this.PaymodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double gross_amount
        {
            get
            {
                return this.gross_amountField;
            }
            set
            {
                this.gross_amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double net_amount
        {
            get
            {
                return this.net_amountField;
            }
            set
            {
                this.net_amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string AuthID
        {
            get
            {
                return this.AuthIDField;
            }
            set
            {
                this.AuthIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string PostDate
        {
            get
            {
                return this.PostDateField;
            }
            set
            {
                this.PostDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string TransID
        {
            get
            {
                return this.TransIDField;
            }
            set
            {
                this.TransIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string RefID
        {
            get
            {
                return this.RefIDField;
            }
            set
            {
                this.RefIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string OrderID
        {
            get
            {
                return this.OrderIDField;
            }
            set
            {
                this.OrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string udf1
        {
            get
            {
                return this.udf1Field;
            }
            set
            {
                this.udf1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string udf2
        {
            get
            {
                return this.udf2Field;
            }
            set
            {
                this.udf2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string udf3
        {
            get
            {
                return this.udf3Field;
            }
            set
            {
                this.udf3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string udf4
        {
            get
            {
                return this.udf4Field;
            }
            set
            {
                this.udf4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string udf5
        {
            get
            {
                return this.udf5Field;
            }
            set
            {
                this.udf5Field = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyFatoorah.Test.PayGatewayServiceV2Soap")]
    public interface PayGatewayServiceV2Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/merchantDC", ReplyAction="*")]
        System.Threading.Tasks.Task<MyFatoorah.Test.merchantDCResponse> merchantDCAsync(MyFatoorah.Test.merchantDCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PayRequestV1", ReplyAction="*")]
        System.Threading.Tasks.Task<MyFatoorah.Test.PayRequestV1Response> PayRequestV1Async(MyFatoorah.Test.PayRequestV1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PayResponse", ReplyAction="*")]
        System.Threading.Tasks.Task<MyFatoorah.Test.PayResponseResponse> PayResponseAsync(MyFatoorah.Test.PayResponseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/total", ReplyAction="*")]
        System.Threading.Tasks.Task<MyFatoorah.Test.totalResponse> totalAsync(MyFatoorah.Test.totalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/paymentMode", ReplyAction="*")]
        System.Threading.Tasks.Task<MyFatoorah.Test.paymentModeResponse> paymentModeAsync(MyFatoorah.Test.paymentModeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/paymentCurrency", ReplyAction="*")]
        System.Threading.Tasks.Task<MyFatoorah.Test.paymentCurrencyResponse> paymentCurrencyAsync(MyFatoorah.Test.paymentCurrencyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fetchPaymentCurrency", ReplyAction="*")]
        System.Threading.Tasks.Task fetchPaymentCurrencyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PaymentRequestv2", ReplyAction="*")]
        System.Threading.Tasks.Task<MyFatoorah.Test.PaymentRequestv2Response> PaymentRequestv2Async(MyFatoorah.Test.PaymentRequestv2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PaymentRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<MyFatoorah.Test.PaymentRequestResponse> PaymentRequestAsync(MyFatoorah.Test.PaymentRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderStatusRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<MyFatoorah.Test.GetOrderStatusRequestResponse> GetOrderStatusRequestAsync(MyFatoorah.Test.GetOrderStatusRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderStatusRequestV2", ReplyAction="*")]
        System.Threading.Tasks.Task<MyFatoorah.Test.GetOrderStatusRequestV2Response> GetOrderStatusRequestV2Async(MyFatoorah.Test.GetOrderStatusRequestV2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class merchantDCRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="merchantDC", Namespace="http://tempuri.org/", Order=0)]
        public MyFatoorah.Test.merchantDCRequestBody Body;
        
        public merchantDCRequest()
        {
        }
        
        public merchantDCRequest(MyFatoorah.Test.merchantDCRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class merchantDCRequestBody
    {
        
        public merchantDCRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class merchantDCResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="merchantDCResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyFatoorah.Test.merchantDCResponseBody Body;
        
        public merchantDCResponse()
        {
        }
        
        public merchantDCResponse(MyFatoorah.Test.merchantDCResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class merchantDCResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MyFatoorah.Test.MerchantDC merchantDCResult;
        
        public merchantDCResponseBody()
        {
        }
        
        public merchantDCResponseBody(MyFatoorah.Test.MerchantDC merchantDCResult)
        {
            this.merchantDCResult = merchantDCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayRequestV1Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayRequestV1", Namespace="http://tempuri.org/", Order=0)]
        public MyFatoorah.Test.PayRequestV1RequestBody Body;
        
        public PayRequestV1Request()
        {
        }
        
        public PayRequestV1Request(MyFatoorah.Test.PayRequestV1RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PayRequestV1RequestBody
    {
        
        public PayRequestV1RequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayRequestV1Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayRequestV1Response", Namespace="http://tempuri.org/", Order=0)]
        public MyFatoorah.Test.PayRequestV1ResponseBody Body;
        
        public PayRequestV1Response()
        {
        }
        
        public PayRequestV1Response(MyFatoorah.Test.PayRequestV1ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PayRequestV1ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MyFatoorah.Test.PayRequestDCV1 PayRequestV1Result;
        
        public PayRequestV1ResponseBody()
        {
        }
        
        public PayRequestV1ResponseBody(MyFatoorah.Test.PayRequestDCV1 PayRequestV1Result)
        {
            this.PayRequestV1Result = PayRequestV1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayResponseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyFatoorah.Test.PayResponseRequestBody Body;
        
        public PayResponseRequest()
        {
        }
        
        public PayResponseRequest(MyFatoorah.Test.PayResponseRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PayResponseRequestBody
    {
        
        public PayResponseRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayResponseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayResponseResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyFatoorah.Test.PayResponseResponseBody Body;
        
        public PayResponseResponse()
        {
        }
        
        public PayResponseResponse(MyFatoorah.Test.PayResponseResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PayResponseResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MyFatoorah.Test.PayResponseDC PayResponseResult;
        
        public PayResponseResponseBody()
        {
        }
        
        public PayResponseResponseBody(MyFatoorah.Test.PayResponseDC PayResponseResult)
        {
            this.PayResponseResult = PayResponseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class totalRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="total", Namespace="http://tempuri.org/", Order=0)]
        public MyFatoorah.Test.totalRequestBody Body;
        
        public totalRequest()
        {
        }
        
        public totalRequest(MyFatoorah.Test.totalRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class totalRequestBody
    {
        
        public totalRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class totalResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="totalResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyFatoorah.Test.totalResponseBody Body;
        
        public totalResponse()
        {
        }
        
        public totalResponse(MyFatoorah.Test.totalResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class totalResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MyFatoorah.Test.TotalDC totalResult;
        
        public totalResponseBody()
        {
        }
        
        public totalResponseBody(MyFatoorah.Test.TotalDC totalResult)
        {
            this.totalResult = totalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class paymentModeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="paymentMode", Namespace="http://tempuri.org/", Order=0)]
        public MyFatoorah.Test.paymentModeRequestBody Body;
        
        public paymentModeRequest()
        {
        }
        
        public paymentModeRequest(MyFatoorah.Test.paymentModeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class paymentModeRequestBody
    {
        
        public paymentModeRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class paymentModeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="paymentModeResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyFatoorah.Test.paymentModeResponseBody Body;
        
        public paymentModeResponse()
        {
        }
        
        public paymentModeResponse(MyFatoorah.Test.paymentModeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class paymentModeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MyFatoorah.Test.PaymentModeDC paymentModeResult;
        
        public paymentModeResponseBody()
        {
        }
        
        public paymentModeResponseBody(MyFatoorah.Test.PaymentModeDC paymentModeResult)
        {
            this.paymentModeResult = paymentModeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class paymentCurrencyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="paymentCurrency", Namespace="http://tempuri.org/", Order=0)]
        public MyFatoorah.Test.paymentCurrencyRequestBody Body;
        
        public paymentCurrencyRequest()
        {
        }
        
        public paymentCurrencyRequest(MyFatoorah.Test.paymentCurrencyRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class paymentCurrencyRequestBody
    {
        
        public paymentCurrencyRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class paymentCurrencyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="paymentCurrencyResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyFatoorah.Test.paymentCurrencyResponseBody Body;
        
        public paymentCurrencyResponse()
        {
        }
        
        public paymentCurrencyResponse(MyFatoorah.Test.paymentCurrencyResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class paymentCurrencyResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MyFatoorah.Test.PaymentCurrencyDC paymentCurrencyResult;
        
        public paymentCurrencyResponseBody()
        {
        }
        
        public paymentCurrencyResponseBody(MyFatoorah.Test.PaymentCurrencyDC paymentCurrencyResult)
        {
            this.paymentCurrencyResult = paymentCurrencyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentRequestv2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PaymentRequestv2", Namespace="http://tempuri.org/", Order=0)]
        public MyFatoorah.Test.PaymentRequestv2RequestBody Body;
        
        public PaymentRequestv2Request()
        {
        }
        
        public PaymentRequestv2Request(MyFatoorah.Test.PaymentRequestv2RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PaymentRequestv2RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MyFatoorah.Test.PayRequestDCV1 req;
        
        public PaymentRequestv2RequestBody()
        {
        }
        
        public PaymentRequestv2RequestBody(MyFatoorah.Test.PayRequestDCV1 req)
        {
            this.req = req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentRequestv2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PaymentRequestv2Response", Namespace="http://tempuri.org/", Order=0)]
        public MyFatoorah.Test.PaymentRequestv2ResponseBody Body;
        
        public PaymentRequestv2Response()
        {
        }
        
        public PaymentRequestv2Response(MyFatoorah.Test.PaymentRequestv2ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PaymentRequestv2ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MyFatoorah.Test.PayResponseDC PaymentRequestv2Result;
        
        public PaymentRequestv2ResponseBody()
        {
        }
        
        public PaymentRequestv2ResponseBody(MyFatoorah.Test.PayResponseDC PaymentRequestv2Result)
        {
            this.PaymentRequestv2Result = PaymentRequestv2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentRequestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PaymentRequest", Namespace="http://tempuri.org/", Order=0)]
        public MyFatoorah.Test.PaymentRequestRequestBody Body;
        
        public PaymentRequestRequest()
        {
        }
        
        public PaymentRequestRequest(MyFatoorah.Test.PaymentRequestRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PaymentRequestRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MyFatoorah.Test.PayRequestDCV1 req;
        
        public PaymentRequestRequestBody()
        {
        }
        
        public PaymentRequestRequestBody(MyFatoorah.Test.PayRequestDCV1 req)
        {
            this.req = req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PaymentRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyFatoorah.Test.PaymentRequestResponseBody Body;
        
        public PaymentRequestResponse()
        {
        }
        
        public PaymentRequestResponse(MyFatoorah.Test.PaymentRequestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PaymentRequestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MyFatoorah.Test.PayResponseDC PaymentRequestResult;
        
        public PaymentRequestResponseBody()
        {
        }
        
        public PaymentRequestResponseBody(MyFatoorah.Test.PayResponseDC PaymentRequestResult)
        {
            this.PaymentRequestResult = PaymentRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderStatusRequestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderStatusRequest", Namespace="http://tempuri.org/", Order=0)]
        public MyFatoorah.Test.GetOrderStatusRequestRequestBody Body;
        
        public GetOrderStatusRequestRequest()
        {
        }
        
        public GetOrderStatusRequestRequest(MyFatoorah.Test.GetOrderStatusRequestRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrderStatusRequestRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MyFatoorah.Test.GetOrderStatusRequestDC getOrderStatusRequestDC;
        
        public GetOrderStatusRequestRequestBody()
        {
        }
        
        public GetOrderStatusRequestRequestBody(MyFatoorah.Test.GetOrderStatusRequestDC getOrderStatusRequestDC)
        {
            this.getOrderStatusRequestDC = getOrderStatusRequestDC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderStatusRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderStatusRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyFatoorah.Test.GetOrderStatusRequestResponseBody Body;
        
        public GetOrderStatusRequestResponse()
        {
        }
        
        public GetOrderStatusRequestResponse(MyFatoorah.Test.GetOrderStatusRequestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrderStatusRequestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MyFatoorah.Test.OrderStatusResponseDC GetOrderStatusRequestResult;
        
        public GetOrderStatusRequestResponseBody()
        {
        }
        
        public GetOrderStatusRequestResponseBody(MyFatoorah.Test.OrderStatusResponseDC GetOrderStatusRequestResult)
        {
            this.GetOrderStatusRequestResult = GetOrderStatusRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderStatusRequestV2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderStatusRequestV2", Namespace="http://tempuri.org/", Order=0)]
        public MyFatoorah.Test.GetOrderStatusRequestV2RequestBody Body;
        
        public GetOrderStatusRequestV2Request()
        {
        }
        
        public GetOrderStatusRequestV2Request(MyFatoorah.Test.GetOrderStatusRequestV2RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrderStatusRequestV2RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MyFatoorah.Test.GetOrderStatusRequestDC getOrderStatusRequestDC;
        
        public GetOrderStatusRequestV2RequestBody()
        {
        }
        
        public GetOrderStatusRequestV2RequestBody(MyFatoorah.Test.GetOrderStatusRequestDC getOrderStatusRequestDC)
        {
            this.getOrderStatusRequestDC = getOrderStatusRequestDC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderStatusRequestV2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderStatusRequestV2Response", Namespace="http://tempuri.org/", Order=0)]
        public MyFatoorah.Test.GetOrderStatusRequestV2ResponseBody Body;
        
        public GetOrderStatusRequestV2Response()
        {
        }
        
        public GetOrderStatusRequestV2Response(MyFatoorah.Test.GetOrderStatusRequestV2ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrderStatusRequestV2ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MyFatoorah.Test.OrderStatusResponseDC GetOrderStatusRequestV2Result;
        
        public GetOrderStatusRequestV2ResponseBody()
        {
        }
        
        public GetOrderStatusRequestV2ResponseBody(MyFatoorah.Test.OrderStatusResponseDC GetOrderStatusRequestV2Result)
        {
            this.GetOrderStatusRequestV2Result = GetOrderStatusRequestV2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface PayGatewayServiceV2SoapChannel : MyFatoorah.Test.PayGatewayServiceV2Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class PayGatewayServiceV2SoapClient : System.ServiceModel.ClientBase<MyFatoorah.Test.PayGatewayServiceV2Soap>, MyFatoorah.Test.PayGatewayServiceV2Soap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PayGatewayServiceV2SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(PayGatewayServiceV2SoapClient.GetBindingForEndpoint(endpointConfiguration), PayGatewayServiceV2SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PayGatewayServiceV2SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PayGatewayServiceV2SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PayGatewayServiceV2SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PayGatewayServiceV2SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PayGatewayServiceV2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyFatoorah.Test.merchantDCResponse> MyFatoorah.Test.PayGatewayServiceV2Soap.merchantDCAsync(MyFatoorah.Test.merchantDCRequest request)
        {
            return base.Channel.merchantDCAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyFatoorah.Test.merchantDCResponse> merchantDCAsync()
        {
            MyFatoorah.Test.merchantDCRequest inValue = new MyFatoorah.Test.merchantDCRequest();
            inValue.Body = new MyFatoorah.Test.merchantDCRequestBody();
            return ((MyFatoorah.Test.PayGatewayServiceV2Soap)(this)).merchantDCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyFatoorah.Test.PayRequestV1Response> MyFatoorah.Test.PayGatewayServiceV2Soap.PayRequestV1Async(MyFatoorah.Test.PayRequestV1Request request)
        {
            return base.Channel.PayRequestV1Async(request);
        }
        
        public System.Threading.Tasks.Task<MyFatoorah.Test.PayRequestV1Response> PayRequestV1Async(PayRequestDCV1 req)
        {
            MyFatoorah.Test.PayRequestV1Request inValue = new MyFatoorah.Test.PayRequestV1Request();
            inValue.Body = new MyFatoorah.Test.PayRequestV1RequestBody();
            return ((MyFatoorah.Test.PayGatewayServiceV2Soap)(this)).PayRequestV1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyFatoorah.Test.PayResponseResponse> MyFatoorah.Test.PayGatewayServiceV2Soap.PayResponseAsync(MyFatoorah.Test.PayResponseRequest request)
        {
            return base.Channel.PayResponseAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyFatoorah.Test.PayResponseResponse> PayResponseAsync()
        {
            MyFatoorah.Test.PayResponseRequest inValue = new MyFatoorah.Test.PayResponseRequest();
            inValue.Body = new MyFatoorah.Test.PayResponseRequestBody();
            return ((MyFatoorah.Test.PayGatewayServiceV2Soap)(this)).PayResponseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyFatoorah.Test.totalResponse> MyFatoorah.Test.PayGatewayServiceV2Soap.totalAsync(MyFatoorah.Test.totalRequest request)
        {
            return base.Channel.totalAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyFatoorah.Test.totalResponse> totalAsync()
        {
            MyFatoorah.Test.totalRequest inValue = new MyFatoorah.Test.totalRequest();
            inValue.Body = new MyFatoorah.Test.totalRequestBody();
            return ((MyFatoorah.Test.PayGatewayServiceV2Soap)(this)).totalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyFatoorah.Test.paymentModeResponse> MyFatoorah.Test.PayGatewayServiceV2Soap.paymentModeAsync(MyFatoorah.Test.paymentModeRequest request)
        {
            return base.Channel.paymentModeAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyFatoorah.Test.paymentModeResponse> paymentModeAsync()
        {
            MyFatoorah.Test.paymentModeRequest inValue = new MyFatoorah.Test.paymentModeRequest();
            inValue.Body = new MyFatoorah.Test.paymentModeRequestBody();
            return ((MyFatoorah.Test.PayGatewayServiceV2Soap)(this)).paymentModeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyFatoorah.Test.paymentCurrencyResponse> MyFatoorah.Test.PayGatewayServiceV2Soap.paymentCurrencyAsync(MyFatoorah.Test.paymentCurrencyRequest request)
        {
            return base.Channel.paymentCurrencyAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyFatoorah.Test.paymentCurrencyResponse> paymentCurrencyAsync()
        {
            MyFatoorah.Test.paymentCurrencyRequest inValue = new MyFatoorah.Test.paymentCurrencyRequest();
            inValue.Body = new MyFatoorah.Test.paymentCurrencyRequestBody();
            return ((MyFatoorah.Test.PayGatewayServiceV2Soap)(this)).paymentCurrencyAsync(inValue);
        }
        
        public System.Threading.Tasks.Task fetchPaymentCurrencyAsync()
        {
            return base.Channel.fetchPaymentCurrencyAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyFatoorah.Test.PaymentRequestv2Response> MyFatoorah.Test.PayGatewayServiceV2Soap.PaymentRequestv2Async(MyFatoorah.Test.PaymentRequestv2Request request)
        {
            return base.Channel.PaymentRequestv2Async(request);
        }
        
        public System.Threading.Tasks.Task<MyFatoorah.Test.PaymentRequestv2Response> PaymentRequestv2Async(MyFatoorah.Test.PayRequestDCV1 req)
        {
            MyFatoorah.Test.PaymentRequestv2Request inValue = new MyFatoorah.Test.PaymentRequestv2Request();
            inValue.Body = new MyFatoorah.Test.PaymentRequestv2RequestBody();
            inValue.Body.req = req;
            return ((MyFatoorah.Test.PayGatewayServiceV2Soap)(this)).PaymentRequestv2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyFatoorah.Test.PaymentRequestResponse> MyFatoorah.Test.PayGatewayServiceV2Soap.PaymentRequestAsync(MyFatoorah.Test.PaymentRequestRequest request)
        {
            return base.Channel.PaymentRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyFatoorah.Test.PaymentRequestResponse> PaymentRequestAsync(MyFatoorah.Test.PayRequestDCV1 req)
        {
            MyFatoorah.Test.PaymentRequestRequest inValue = new MyFatoorah.Test.PaymentRequestRequest();
            inValue.Body = new MyFatoorah.Test.PaymentRequestRequestBody();
            inValue.Body.req = req;
            return ((MyFatoorah.Test.PayGatewayServiceV2Soap)(this)).PaymentRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyFatoorah.Test.GetOrderStatusRequestResponse> MyFatoorah.Test.PayGatewayServiceV2Soap.GetOrderStatusRequestAsync(MyFatoorah.Test.GetOrderStatusRequestRequest request)
        {
            return base.Channel.GetOrderStatusRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyFatoorah.Test.GetOrderStatusRequestResponse> GetOrderStatusRequestAsync(MyFatoorah.Test.GetOrderStatusRequestDC getOrderStatusRequestDC)
        {
            MyFatoorah.Test.GetOrderStatusRequestRequest inValue = new MyFatoorah.Test.GetOrderStatusRequestRequest();
            inValue.Body = new MyFatoorah.Test.GetOrderStatusRequestRequestBody();
            inValue.Body.getOrderStatusRequestDC = getOrderStatusRequestDC;
            return ((MyFatoorah.Test.PayGatewayServiceV2Soap)(this)).GetOrderStatusRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyFatoorah.Test.GetOrderStatusRequestV2Response> MyFatoorah.Test.PayGatewayServiceV2Soap.GetOrderStatusRequestV2Async(MyFatoorah.Test.GetOrderStatusRequestV2Request request)
        {
            return base.Channel.GetOrderStatusRequestV2Async(request);
        }
        
        public System.Threading.Tasks.Task<MyFatoorah.Test.GetOrderStatusRequestV2Response> GetOrderStatusRequestV2Async(MyFatoorah.Test.GetOrderStatusRequestDC getOrderStatusRequestDC)
        {
            MyFatoorah.Test.GetOrderStatusRequestV2Request inValue = new MyFatoorah.Test.GetOrderStatusRequestV2Request();
            inValue.Body = new MyFatoorah.Test.GetOrderStatusRequestV2RequestBody();
            inValue.Body.getOrderStatusRequestDC = getOrderStatusRequestDC;
            return ((MyFatoorah.Test.PayGatewayServiceV2Soap)(this)).GetOrderStatusRequestV2Async(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PayGatewayServiceV2Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.PayGatewayServiceV2Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PayGatewayServiceV2Soap))
            {
                return new System.ServiceModel.EndpointAddress("https://test.myfatoorah.com/pg/PayGatewayServicev2.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.PayGatewayServiceV2Soap12))
            {
                return new System.ServiceModel.EndpointAddress("https://test.myfatoorah.com/pg/PayGatewayServicev2.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            PayGatewayServiceV2Soap,
            
            PayGatewayServiceV2Soap12,
        }
    }
}
